skills_domain = [
    "hubspot","latex"
    # Programming Languages
    "python", "java", "javascript", "c++", "c#", "c", "r", "sql", "php", "ruby",
    "swift", "kotlin", "go", "rust", "typescript", "scala", "perl", "matlab", "octave",
    # Web Technologies
    "html", "css", "react", "angular", "vue", "node.js", "express", "django",
    "flask", "spring", "bootstrap", "jquery", "webgl", "web3","html5","css3",
    # Databases
    "mysql", "postgresql", "mongodb", "sqlite", "oracle", "redis", "cassandra",
    "hibernate", "jpa", "entity framework", "sequelize", "prisma", "sqlalchemy",
    # Cloud & DevOps
    "aws", "azure", "google cloud", "docker", "kubernetes", "jenkins", "git", "celery",
    "terraform", "ansible", "ci/cd", "devops", "aws sagemaker", "google ai platform",
    "azure machine learning", "mlops", "container orchestration", "load balancing",
    "auto-scaling", "serverless architecture", "lambda functions", "azure functions",
    "google cloud functions", "api gateway", "message queues", "pub/sub",
    "event-driven architecture", "microservices architecture", "site reliability",
    "observability", "monitoring", "logging", "alerting", "incident management",
    "post-mortem analysis", "root cause analysis", "service level agreements", "slas",
    "service level objectives", "slos", "sonarqube", "artifactory", "nexus", "maven",
    "gradle", "npm", "yarn", "pip", "conda", "virtual environments", "devsecops",
    # Data Science & Machine Learning
    "machine learning", "deep learning", "tensorflow", "pytorch", "scikit-learn",
    "pandas", "numpy", "matplotlib", "seaborn", "jupyter", "data analysis",
    "statistical analysis", "data visualization", "predictive modeling", "data cleaning",
    "report generation", "business intelligence", "a/b testing", "spss", "sas",
    "hypothesis testing", "regression analysis", "anova", "probability theory",
    "experimental design", "data interpretation", "sampling techniques",
    "quantitative research", "statistical modeling", "natural language processing", "nlp",
    "computer vision", "image processing", "neural networks", "reinforcement learning",
    "feature engineering", "model deployment", "data governance", "data privacy",
    "gdpr compliance", "ccpa compliance", "data mining", "text mining", "nlp engineering",
    "deep learning engineering", "ai research", "ml research", "cv research", "nlp research",
    "data science", "data engineering", "feature store", "model monitoring",
    "model governance", "explainable ai", "xai", "fairness in ai", "responsible ai",
    "ethical ai", "privacy-preserving ai", "federated learning", "differential privacy",
    "homomorphic encryption", "secure multi-party computation", "data librarianship",
    "data quality", "master data management", "mdm", "data stewardship", "data curation",
    "research data management", "open science", "fair principles", "reproducible research",
    "research software engineering", "data science engineering", "machine learning engineering",
    "r programming", "sas programming", "spss programming", "stata", "simulink", "mle", "mlo",
    # Design & Multimedia
    "adobe creative suite", "adobe photoshop", "adobe premiere", "adobe xd", "illustrator","photoshop",
    "figma", "sketch", "corel draw", "final cut pro", "ux design", "ui design",
    "wireframing", "prototyping", "user research", "usability testing",
    "information architecture", "interaction design", "visual design", "typography",
    "color theory", "branding", "graphic design", "motion graphics", "video editing",
    "audio production", "podcast production", "live streaming", "3d modeling",
    "cad software", "autocad", "solidworks", "revit", "sketchup", "blender", "maya",
    "cinema 4d", "zbrush", "substance painter", "unity 3d", "game design", "level design",
    "character design", "environmental design", "game mechanics", "game balancing",
    "monetization strategies", "game analytics", "vr development", "ar development",
    "mixed reality", "extended reality", "xr", "haptics", "spatial computing",
    "game engine development", "physics engine development", "rendering", "shading languages",
    "opengl", "directx", "vulkan", "game development frameworks", "unity editor",
    "unreal editor", "blender scripting", "maya scripting", "substance designer",
    "zbrush sculpting", "marvelous designer", "houdini", "nuke", "after effects", "audition",
    "indesign", "acrobat pro", "figma prototyping", "sketch design", "invision", "zeplin",
    "abstract", "framer", "principle", "origami studio", "lottie", "spine", "dragonbones",
    "sprite animation", "ui animation", "motion graphics design", "video editing software",
    "audio editing software", "digital audio workstations", "daws", "pro tools", "logic pro",
    "ableton live", "fl studio", "cubase", "reaper", "audacity", "sound design",
    "music production", "composition", "mastering", "mixing", "audio engineering",
    "live sound", "acoustics", "room treatment", "microphone techniques",
    "recording studio setup", "music theory", "harmony", "counterpoint", "orchestration",
    # Development Tools & IDEs
    "xcode", "visual studio", "intellij idea", "eclipse", "netbeans", "atom", "sublime text",
    "vscode", "vim", "emacs", "notepad++", "brackets", "webstorm", "phpstorm", "pycharm",
    "rider", "clion", "android studio", "xamarin", "flutter", "react native",
    # Project Management
    "agile", "scrum", "kanban", "waterfall", "lean", "six sigma", "jira", "confluence",
    "slack", "trello", "asana", "project planning", "resource allocation",
    "team leadership", "stakeholder management", "agile methodologies", "gantt charts",
    "project tracking", "scrum master", "product owner", "xp", "lean startup",
    "design sprints", "hackathon organization", "innovation labs", "pmp", "csm",
    "prince2", "agile coaching", "facilitation", "change management",
    "organizational development", "strategic planning", "innovation management",
    "open innovation", "design thinking", "human-centered design", "service design",
    "experience design", "customer journey mapping", "user stories", "agile development",
    "r&d management",
    # Business & Office
    "microsoft office", "ms office", "g suite", "microsoft 365", "sharepoint", "excel",
    "powerbi", "tableau", "data storytelling", "presentation design",
    "visual communication", "infographics", "data narrative", "storytelling with data",
    "key performance indicators", "kpis", "metrics", "dashboards", "reporting",
    # Security
    "cybersecurity", "networking", "blockchain", "iot", "network administration",
    "information security", "cyber threat intelligence", "vulnerability assessments",
    "penetration testing", "incident response", "security auditing", "network security",
    "endpoint security", "firewall management", "intrusion detection systems", "ids",
    "intrusion prevention systems", "ips", "encryption", "data loss prevention", "dlp",
    "identity & access management", "iam", "single sign-on", "sso",
    "multi-factor authentication", "mfa", "physical security", "disaster recovery",
    "business continuity planning", "regulatory compliance","wireshark", "metasploit","kali linux",
    # Software Engineering & Testing
    "quality assurance", "software testing", "test automation", "unit testing",
    "integration testing", "system testing", "user acceptance testing", "uat",
    "performance testing", "security testing", "manual testing", "test case design",
    "bug tracking", "test management tools", "selenium", "cypress", "playwright",
    "jmeter", "loadrunner", "domain-driven design", "ddd", "object-oriented programming",
    "oop", "functional programming", "data structures", "algorithms", "design patterns",
    "clean code", "refactoring", "version control", "code reviews", "end-to-end testing",
    "ci/cd pipelines",
    # Finance & Accounting
    "accounting", "financial analysis", "finance", "budget management", "financial modeling",
    "forecasting", "auditing", "compliance", "risk assessment", "fraud detection",
    "investment banking", "corporate finance", "equity research", "fixed income",
    "portfolio management", "asset management", "wealth management", "mergers & acquisitions",
    "valuation", "fundraising", "bookkeeping", "accounts payable", "accounts receivable",
    "payroll processing", "basel iii", "solvency ii", "dodd-frank act",
    "sarbanes-oxley act", "sox compliance", "anti-money laundering", "aml",
    "know your customer", "kyc", "financial crime compliance", "regulatory reporting",
    "risk appetite framework", "enterprise risk management", "erm",
    "operational risk management", "credit risk management", "market risk management",
    "liquidity risk management", "model risk management", "cyber risk management",
    "information security risk management", "business continuity management",
    # Sales & Marketing
    "marketing", "marketing strategy", "business development", "sales management",
    "client acquisition", "negotiation", "contract management", "digital marketing",
    "seo", "sem", "smm", "content marketing", "email marketing", "campaign management",
    "brand management", "public relations", "advertising", "google ads", "facebook ads",
    "google analytics", "copywriting", "social media management", "community management",
    "content creation", "blogging", "editing", "proofreading", "technical documentation",
    "report writing", "grant writing", "journalism", "crisis communication",
    "media relations", "event management", "fundraising campaigns", "non-profit management",
    "cause marketing", "experiential marketing", "guerrilla marketing",
    "influencer marketing", "affiliate marketing", "partnership marketing",
    "brand partnerships", "sponsorship management", "event marketing",
    "trade show planning", "webinar hosting", "video production", "animation",
    "digital product development", "saas marketing", "b2b marketing", "b2c marketing",
    "non-profit marketing", "customer segmentation", "customer retention",
    "customer loyalty", "web analytics", "google analytics 4", "adobe analytics",
    "mixpanel", "amplitude", "segment", "tag management", "google tag manager",
    "seo auditing", "keyword research", "link building", "technical seo", "local seo",
    "app store optimization", "aso", "search engine marketing", "pay-per-click", "ppc",
    "google ads campaigns", "bing ads", "social media advertising",
    "facebook ads manager", "instagram ads", "linkedin ads", "twitter ads",
    "pinterest ads", "tiktok ads", "youtube advertising", "display advertising",
    "native advertising", "programmatic advertising", "ad serving", "ad tech",
    "marketing automation", "email marketing platforms", "crm integration",
    "lead nurturing", "drip campaigns", "marketing funnel optimization",
    "content strategy", "content calendar", "blogging platforms", "cms", "wordpress",
    "shopify", "magento", "drupal", "joomla", "wix", "squarespace",
    "e-commerce platforms", "online marketplaces", "amazon seller central",
    "ebay selling", "etsy shop management", "communication strategy",
    "marketing communications", "integrated marketing", "brand awareness",
    "brand positioning", "product launch", "market segmentation",
    "target audience analysis", "competitive analysis", "pricing strategy",
    "distribution channels", "sales forecasting", "sales operations", "crm administration",
    # Supply Chain & Operations
    "inventory management", "supply chain management", "logistics", "procurement",
    "quality control", "process improvement", "lean six sigma", "supply chain optimization",
    "logistics management system", "warehouse management system",
    "transportation management system", "route optimization", "fleet management",
    "inventory optimization", "demand forecasting", "supply planning",
    "production planning", "operations research", "linear programming",
    "optimization algorithms", "simulation modeling", "discrete-event simulation",
    "monte carlo simulation", "six sigma green belt", "six sigma black belt",
    "lean manufacturing", "total quality management", "tqm", "iso 9001", "iso 27001",
    # Healthcare & Medical
    "patient care", "electronic health records", "ehr", "pharmacology", "hipaa",
    "diagnostic testing", "patient education", "clinical research", "data management",
    "epidemiology", "public health", "health policy", "health economics",
    "health outcomes research", "health services research", "patient safety",
    "quality improvement in healthcare", "infection control", "hospital administration",
    "healthcare management", "nursing management", "clinic management",
    "practice management", "medical billing & coding", "medical office administration",
    "healthcare information systems", "health technology assessment", "medical ethics",
    "bioethics", "medical law", "patient rights", "informed consent", "confidentiality",
    "hipaa privacy rule", "hipaa security rule", "osha compliance", "clia regulations",
    "joint commission standards", "accreditation management", "licensing & certification",
    "professional development", "continuing medical education", "cme",
    "nursing professional development", "npd", "medical education", "health education",
    "community health education", "health promotion", "wellness programs",
    "preventive medicine", "chronic disease management", "acute care",
    "rehabilitation services", "physical therapy", "occupational therapy",
    "speech therapy", "respiratory therapy", "dietetics", "nutrition counseling",
    "social work", "counseling", "psychotherapy", "mental health counseling",
    "substance abuse counseling", "crisis intervention", "family therapy", "group therapy",
    "child therapy", "adolescent therapy", "trauma-informed care",
    "cognitive behavioral therapy", "cbt", "dialectical behavior therapy", "dbt",
    "mindfulness-based stress reduction", "mbsr", "acceptance and commitment therapy", "act",
    "psychiatric nursing", "clinical psychology", "forensic psychology",
    "organizational psychology", "sports psychology", "educational psychology",
    "school psychology", "neuropsychology", "developmental psychology",
    "social psychology", "experimental psychology", "research methodology",
    "statistical software", "rstudio", "jamovi", "jasp", "mplus", "amos", "lisrel",
    "smartpls", "maxqda", "nvivo", "atlas.ti", "qualitative data analysis",
    "thematic analysis", "content analysis", "discourse analysis", "grounded theory",
    "ethnography", "case study research", "action research", "mixed methods research",
    "survey research", "quasi-experimental design", "evaluation research",
    "program evaluation", "outcome measurement", "impact assessment",
    "cost-benefit analysis", "social impact assessment", "environmental impact assessment",
    "sustainability reporting", "esg reporting", "corporate social responsibility", "csr",
    "ethical sourcing", "circular economy", "green building", "renewable energy",
    "climate change mitigation", "adaptation strategies", "environmental policy",
    "conservation", "biodiversity", "ecology", "geography", "gis", "remote sensing",
    "cartography", "urban planning", "regional planning", "community development",
    "affordable housing", "transportation planning", "public administration",
    "social enterprise", "philanthropy", "grant management", "fundraising strategy",
    "donor relations", "volunteer recruitment", "community engagement", "advocacy",
    "lobbying", "policy analysis", "public policy", "international relations",
    "diplomacy", "foreign policy", "human rights", "international development",
    "peacebuilding", "humanitarian aid", "disaster relief", "refugee assistance",
    "migration studies", "global governance", "international law", "trade agreements",
    "economic development", "poverty reduction", "microfinance", "social justice",
    "equality", "diversity, equity, and inclusion", "intercultural communication",
    "cross-cultural training", "globalization", "sustainable development goals", "sdgs",
    "united nations", "ngo management", "civil society organizations",
    "research administration", "grants management", "compliance oversight",
    "ethics review", "institutional review board", "irb",
    "animal care and use committee", "iacuc", "export control compliance",
    "research integrity", "scientific publishing", "peer review", "academic writing",
    "scholarly communication", "library science", "information literacy",
    "archives management", "records management", "knowledge management",
    "content management", "digital asset management", "dam",
    "document management systems", "dms", "enterprise content management", "ecm",
    "web content management", "wcm", "metadata management", "taxonomy development",
    "controlled vocabularies", "ontology engineering", "semantic web", "linked data",
    "communication", "public speaking", "presentation skills",
    # Legal
    "estate planning", "trust administration", "litigation", "medicaid planning",
    "asset protection", "will drafting", "advance directives", "court appearances",
    "legal counsel", "law practice", "juris doctor", "jd", "legal research",
    "document drafting", "health care proxies",
    # Other
    "robotics", "automation", "mechatronics", "control systems", "sensors",
    "actuators", "embedded systems", "firmware development", "hardware design",
    "circuit design", "pcb design", "fpga programming", "asic design", "signal processing",
    "computer graphics"
]
