# Generated by Django 5.2.8 on 2025-11-20 11:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_matcher', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='savedjob',
            unique_together={('user', 'job_title', 'company_name')},
        ),
    ]
