# Generated by Django 5.2.8 on 2025-11-21 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_matcher', '0002_alter_savedjob_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedjob',
            name='job_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
